const express = require("express")
const db = require("./../dbConnections/sqldb")
const path = require("path")
const Router = express.Router()
const studentController = require('../controllers/studentsController.js')
Router.get("/", studentController.studentsPage)
Router.get('/new', studentController.newStudent)
Router.get("/add", studentController.addStudent)
Router.get("/showStudents", studentController.showStudents)
Router.get("/search", studentController.searchStudents)
  module.exports = Router