const express = require("express")
const db = require("./../dbConnections/sqldb")
const path = require("path")
const Router = express.Router()
const studentController = require('../controllers/studentsController.js')
Router.get("/", studentController.studentsPage)
Router.get('/register', studentController.register)
Router.get("/register", studentController.registerPost)
Router.get("/showStudents", studentController.showStudents)
Router.get("/search", studentController.searchStudents)
Router.get('/login', studentController.login)
Router.post('/login', studentController.loginPost)
Router.get('/logout', studentController.logout)
Router.get('/forgot', studentController.forgot)
Router.post('/forgot', studentController.forgotPost)
Router.post('/forgot/varify', studentController.varifyOtp)
module.exports = Router